# Generated by Django 5.2.4 on 2025-07-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, unique=True, verbose_name="Заголовок")),
                ("entry", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="blog_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("view_counter", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
                "db_table": "article",
                "ordering": ["title"],
            },
        ),
    ]
